### ISSUE TITLE
Clarify if/when to regenerate manifest template

### ISSUE THREAD

**Issue by aclayton555** [ncihtan/HTAN-Data-Ingress-Docs#23]
This issue relates to the issue described here: https://sagebionetworks.jira.com/browse/HTAN-43

Within the internal comments of the issue above, Milen has suggested some clarifying content to include in the docs.

**Comment by linglp** [comment]
@aclayton555 could you give me access to JIRA HTAN page? I don't think I could open the link above

**Comment by aclayton555** [comment]
Thanks for letting me know! You should now be added - you may have received an email from the Jira system, and I am not sure if you need to "accept" anything to join

**Comment by milen-sage** [comment]
PR approved #28.

**Comment by aclayton555** [comment]
@milen-sage or @linglp  can you please point me to where in the documentation I can find the update to address this, so I can point to original customer to this and close the loop here in the Jira ticket above? Thanks.

**Comment by linglp** [comment]
@aclayton555 Same as #22 You could find the link here: https://ncihtan.github.io/HTAN-Data-Ingress-Docs/

**Comment by milen-sage** [comment]
@aclayton555 see the new bullet point list [here](https://ncihtan.github.io/HTAN-Data-Ingress-Docs/step-2.html#generate-an-empty-template). And the `Before you start` section [here](https://ncihtan.github.io/HTAN-Data-Ingress-Docs/update-existing-metadata.html)
